### ISSUE TITLE
Huge run times with bigger datasets

### ISSUE THREAD

**Issue by ghost** [viadee/magie#4] opened 2020-09-10 14:05 UTC
Hi @NoItAll , 

I am running MAGIE on a dataset with more than 100,000 rows. The code keeps on running for more than an hour. Could you suggest how to speed up the code for bigger datasets.

**Comment by NoItAll** [comment] 2020-09-10 14:21
Perhaps you could further specify what dataset you used, which algorithm takes long, etc.? The log should usually contain times. For all hardware I have ever executed MAGIE on, for large data sets (e.g. Skin), the training-phase took the longest. This is not dealt with in MAGIE since training and explanation are two separate issues (at least they are not integrated in MAGIE). However, even then an hour seems very long (in my experience, it should mostly run in few minutes).

**Comment by NoItAll** [comment] 2020-09-14 08:55
Hello @adityakumar04 ,

are there any updates from your part?
Otherwise I would close this issue.

Best regards

**Comment by ghost** [comment] 2020-09-14 09:16
Hi @NoItAll : Extremely sorry for the late reply. I somehow missed the notification. 

The dataset that I am using is confidential hence I cannot reveal information about it. However, When I run this using eclipse on a 8gb machine and the number of rows is more than 100,000 rows, then it keeps on running for more than an hour. The model itself does not get initiated in the console log. As soon as I shift to a smaller dataset (~10k rows) the run times are less than 5 minutes

**Comment by NoItAll** [comment] 2020-09-14 11:25
What about the number of columns, the data types, ...? Are you sure you correctly read the dataset using AnchorTabular? Usually, if a step is executed, the execution time is printed (e.g. [here](https://github.com/viadee/magie/blob/master/src/main/java/de/viadee/xai/framework/explanation_pipeline/ExplanationPipeline.java#L490)), so I think that either the model training or the data loading itself takes too long.

**Comment by NoItAll** [comment] 2020-09-23 13:47
I assume the problem is resolved.

**Comment by ghost** [comment] 2020-09-28 09:31
Hi @NoItAll , Apologies for not paying much attention here. I was extremely held up with something but now I am back to MAGIE experiments. This problem is resolved. Thanks !

**Comment by NoItAll** [comment] 2020-09-28 11:16
Hello @adityakumar04 ,
Could you perhaps share how you dealt with the issue/what the issue was? This might help me to fix this.

**Closed as completed** 2020-10-13 14:45 UTC
